keyboard = require "keyboard"

local keymap = {}

keymap.mapping = {
	KEYMAP_FORWARD = 0,
	KEYMAP_BACKWARD = 1,
	KEYMAP_TURN_LEFT = 2,
	KEYMAP_TURN_RIGHT = 3,
	KEYMAP_SIDESTEP = 4,
	KEYMAP_RUN = 5,
	KEYMAP_JUMP = 6,
	KEYMAP_ACTIVATE = 7,
	KEYMAP_OPEN = 7,
	KEYMAP_ATTACK = 8,
	KEYMAP_USE = 8,
	KEYMAP_LOOK_UP = 9,
	KEYMAP_LOOK_DOWN = 10,
	KEYMAP_READJUST_VIEW = 11,
	KEYMAP_CAST_SPELL = 12,
	KEYMAP_ABORT_SPELL = 13,
	KEYMAP_RUNE1 = 14,
	KEYMAP_RUNE2 = 15,
	KEYMAP_RUNE3 = 16,
	KEYMAP_RUNE4 = 17,
	KEYMAP_RUNE5 = 18,
	KEYMAP_RUNE6 = 19,
	KEYMAP_RUNE7 = 20,
	KEYMAP_RUNE8 = 21,
	KEYMAP_RUNE9 = 22,
	KEYMAP_LOOK_MODE = 23,
	KEYMAP_INVENTORY = 24,
	KEYMAP_EQUIPMENT = 25,
	KEYMAP_STATISTICS = 26,
	KEYMAP_OPTIONS = 27,
	KEYMAP_COMMUNICATE = 28,
	KEYMAP_FINANCES = 29,
	KEYMAP_AMMUNITION = 30,
	KEYMAP_NOTES = 31,
	KEYMAP_JOURNAL = 32,
	KEYMAP_TALK = 33,
	KEYMAP_ABORT_LEVEL = 34,
	KEYMAP_PAUSE_GAME = 35,
	KEYMAP_CANNED_MESSAGE_1 = 36,
	KEYMAP_CANNED_MESSAGE_2 = 37,
	KEYMAP_CANNED_MESSAGE_3 = 38,
	KEYMAP_CANNED_MESSAGE_4 = 39,
	KEYMAP_CANNED_MESSAGE_5 = 40,
	KEYMAP_CANNED_MESSAGE_6 = 41,
	KEYMAP_CANNED_MESSAGE_7 = 42,
	KEYMAP_CANNED_MESSAGE_8 = 43,
	KEYMAP_CANNED_MESSAGE_9 = 44,
	KEYMAP_CANNED_MESSAGE_10 = 45,
	KEYMAP_CANNED_MESSAGE_11 = 46,
	KEYMAP_CANNED_MESSAGE_12 = 47,
	KEYMAP_MAP_DISPLAY = 48,
	KEYMAP_MAP_ROTATE = 49,
	KEYMAP_MAP_TRANSLUCENT = 50,
	KEYMAP_MAP_SEE_THROUGH = 51,
	KEYMAP_MAP_SMALLER_SCALE = 52,
	KEYMAP_MAP_BIGGER_SCALE = 53,
	KEYMAP_MAP_POSITION = 54,
	
	KEYMAP_SCROLL_MSG_UP = 55,
	KEYMAP_SCROLL_MSG_DOWN = 56,
	KEYMAP_TIME_OF_DAY = 57,
	
	KEYMAP_GAMMA_CORRECT = 58,
	KEYMAP_UNKNOWN_EXTRA = 59,
	KEYMAP_ACTIVATE_OR_TAKE = 7,
	
	KEYMAP_NUM_KEYS_MAPPED = 68,
}

local aakeymap = require "aakeymap";

function keymap.getScanCode(keymapping)
	return aakeymap.GetScan(keymapping);
end

-- Takes in a keymapping and returns a key scan code
function keymap.getMap(keymapping)
	return aakeymap.GetMap(keymapping);
end

return keymap
