qrotate B_D_07.PIC 
qrotate B_H_01.PIC 
qrotate B_H_02.PIC 
qrotate B_H_03.PIC 
qrotate B_H_04.PIC 
qrotate B_H_05.PIC 
qrotate B_I_01.PIC 
qrotate B_I_02.PIC 
qrotate B_I_03.PIC 
qrotate B_I_04.PIC 
qrotate B_W_01.PIC 
qrotate B_W_02.PIC 
qrotate B_W_03.PIC 
qrotate B_W_04.PIC 
qrotate BS_A_01.PIC 
qrotate BS_A_02.PIC 
qrotate BS_A_03.PIC 
qrotate BS_A_04.PIC 
qrotate BS_D_01.PIC 
qrotate BS_D_02.PIC 
qrotate BS_D_03.PIC 
qrotate BS_D_04.PIC 
qrotate BS_D_05.PIC 
qrotate BS_D_06.PIC 
qrotate BS_D_07.PIC 
qrotate BS_H_01.PIC 
qrotate BS_H_02.PIC 
qrotate BS_H_03.PIC 
qrotate BS_H_04.PIC 
qrotate BS_H_05.PIC 
qrotate BS_I_01.PIC 
qrotate BS_I_02.PIC 
qrotate BS_I_03.PIC 
qrotate BS_I_04.PIC 
qrotate BS_W_01.PIC 
qrotate BS_W_02.PIC 
qrotate BS_W_03.PIC 
qrotate BS_W_04.PIC 
qrotate F_A_01.PIC 
qrotate F_A_02.PIC 
qrotate F_A_03.PIC 
qrotate F_A_04.PIC 
qrotate F_D_01.PIC 
qrotate F_D_02.PIC 
qrotate F_D_03.PIC 
qrotate F_D_04.PIC 
qrotate F_D_05.PIC 
qrotate F_D_06.PIC 
qrotate F_D_07.PIC 
qrotate F_H_01.PIC 
qrotate F_H_02.PIC 
qrotate F_H_03.PIC 
qrotate F_H_04.PIC 
qrotate F_H_05.PIC 
qrotate F_I_01.PIC 
qrotate F_I_02.PIC 
qrotate F_I_03.PIC 
qrotate F_I_04.PIC 
qrotate F_W_01.PIC 
qrotate F_W_02.PIC 
qrotate F_W_03.PIC 
qrotate F_W_04.PIC 
qrotate FS_A_01.PIC 
qrotate FS_A_02.PIC 
qrotate FS_A_03.PIC 
qrotate FS_A_04.PIC 
qrotate FS_D_01.PIC 
qrotate FS_D_02.PIC 
qrotate FS_D_03.PIC 
qrotate FS_D_04.PIC 
qrotate FS_D_05.PIC 
qrotate FS_D_06.PIC 
qrotate FS_D_07.PIC 
qrotate FS_H_01.PIC 
qrotate FS_H_02.PIC 
qrotate FS_H_03.PIC 
qrotate FS_H_04.PIC 
qrotate FS_H_05.PIC 
qrotate FS_I_01.PIC 
qrotate FS_I_02.PIC 
qrotate FS_I_03.PIC 
qrotate FS_I_04.PIC 
qrotate FS_W_01.PIC 
qrotate FS_W_02.PIC 
qrotate FS_W_03.PIC 
qrotate FS_W_04.PIC 
qrotate L_A_01.PIC 
qrotate L_A_02.PIC 
qrotate L_A_03.PIC 
qrotate L_A_04.PIC 
qrotate L_D_01.PIC 
qrotate L_D_02.PIC 
qrotate L_D_03.PIC 
qrotate L_D_04.PIC 
qrotate L_D_05.PIC 
qrotate L_D_06.PIC 
qrotate L_D_07.PIC 
qrotate L_H_01.PIC 
qrotate L_H_02.PIC 
qrotate L_H_03.PIC 
qrotate L_H_04.PIC 
qrotate L_H_05.PIC 
qrotate L_I_01.PIC 
qrotate L_I_02.PIC 
qrotate L_I_03.PIC 
qrotate L_I_04.PIC 
qrotate L_W_01.PIC 
qrotate L_W_02.PIC 
qrotate L_W_03.PIC 
qrotate L_W_04.PIC 
qrotate B_A_01.PIC 
qrotate B_A_02.PIC 
qrotate B_A_03.PIC 
qrotate B_A_04.PIC 
qrotate B_D_01.PIC 
qrotate B_D_02.PIC 
qrotate B_D_03.PIC 
qrotate B_D_04.PIC 
qrotate B_D_05.PIC 
qrotate B_D_06.PIC 
