characterClasses = {
	Citizen = {
		class = "Citizen",
		attributes = {
			strength = 25,
			speed = 25,
			magic = 25,
			accuracy = 25,
			stealth = 25,
			constitution = 25,
		},
		titles = {
			"Serviceman",
			"Color Bearer",
			"King's Militia",
			"Loyalist",
			"Crown's Servant",
			"Crown's Fighter",
			"Warrior",
			"Defender",
			"Noble",
			"Royal Courtsman",
			"Brigade Elmore",
			"Righteous Band",
			"League of Aeneas",
			"Esias's Servant",
			"Exalted Guardian",
			"Hero",
			"Court Knight",
			"Guard Commander",
			"Supreme General",
			"The Mighty"
		},
		advancement = {
			strength = 2,
			speed = 2,
			magic = 2,
			accuracy = 2,
			stealth = 2,
			constitution = 2,
		},
	},
	Knight = {
		class = "Knight",
		attributes = {
			strength = 35,
			speed = 15,
			magic = 10,
			accuracy = 20,
			stealth = 15,
			constitution = 35,
		},
		titles =  {
			"Page",
			"Trainee",
			"Squire",
			"Swordsman",
			"Enlisted Servant",
			"Tactical Student",
			"Swordsmaster",
			"Court Guard",
			"Armsmaster",
			"Knight",
			"Sect of Elmore",
			"Royal Captain",
			"Royal General",
			"King's Guardian",
			"Vanquisher",
			"Sword of Titas",
			"Glory of Aelia",
			"Horn of Domitian",
			"Title of Omega",
			"Dragonslayer"
		},
		advancement = {
			strength = 3,
			speed = 2,
			magic = 1,
			accuracy = 2,
			stealth = 1,
			constitution = 3,
		},
	},
	Mage = {
		class = "Mage",
		attributes = {
			strength = 10,
			speed = 25,
			magic = 35,
			accuracy = 25,
			stealth = 20,
			constitution = 15,
		},
		titles = {
			"Student",
			"Apprentice",
			"Spellcaster",
			"Mage",
			"Conjurer",
			"Enchanter",
			"Wizard",
			"Lore Master",
			"Dark Spirit",
			"Black Art Scribe",
			"Black Art Master",
			"Magi of the Fire",
			"Magi of the Star",
			"Sorcerer",
			"Order of Nu'ak",
			"Order of Tul",
			"Order of Ahnul",
			"Order of Baal",
			"Prophet of Baal",
			"Ancient One"
		},
		advancement = {
			strength = 1,
			speed = 2,
			magic = 3,
			accuracy = 3,
			stealth = 2,
			constitution = 1,
		},
	},
	Warlock = {
		class = "Warlock",
		attributes = {
			strength = 25,
			speed = 20,
			magic = 30,
			accuracy = 20,
			stealth = 15,
			constitution = 20,
		},
		titles = {
			"Disciple",
			"Apprentice",
			"Dark Artesian",
			"Warlock",
			"Mighty Sword",
			"Vanquisher",
			"Legion",
			"Destroyer",
			"Mystic Conquerer",
			"1st Circle Order",
			"2nd Circle Order",
			"3rd Circle Order",
			"Summoner",
			"Seeker",
			"Destructor",
			"Desolator",
			"Dragon Spirit",
			"Ruiner",
			"Death's Follower",
			"Death Incarnate"
		},
		advancement = {
			strength = 2,
			speed = 2,
			magic = 2,
			accuracy = 2,
			stealth = 2,
			constitution = 2,
		},
	},
	Priest = {
		class = "Priest",
		attributes = {
			strength = 15,
			speed = 20,
			magic = 35,
			accuracy = 15,
			stealth = 20,
			constitution = 25,
		},
		titles = {
			"Flock Tender",
			"Student",
			"Scribe",
			"Teacher",
			"Evangelist",
			"Cleric",
			"Elder",
			"The Annointed",
			"Parable Master",
			"Master of Canon",
			"Bishop",
			"Minor Prophet",
			"Cross Bearer",
			"Disciple",
			"Sacred Branch",
			"Witness",
			"Apostle",
			"Saint",
			"Herald of Glory",
			"Illuminated One"
		},
		advancement = {
			strength = 2,
			speed = 1,
			magic = 3,
			accuracy = 2,
			stealth = 2,
			constitution = 2,
		},
	},
	Rogue = {
		class = "Rogue",
		attributes = {
			strength = 15,
			speed = 30,
			magic = 15,
			accuracy = 25,
			stealth = 30,
			constitution = 15,
		},
		titles = {
			"Sneak",
			"Shadow",
			"Pickpocket",
			"Rogue",
			"Trickster",
			"Contriver",
			"Thief",
			"Knave",
			"Skilled Con",
			"Scoundrel",
			"Nighthawk",
			"Teacher",
			"1st Sect Member",
			"2nd Sect Member",
			"3rd Sect Member",
			"Master of the Art",
			"Stealth Master",
			"The Upright",
			"Master Thief",
			"Legendary Delver"
		},
		advancement = {
			strength = 2,
			speed = 2,
			magic = 1,
			accuracy = 2,
			stealth = 3,
			constitution = 2,
		},
	},
	Archer = {
		class = "Archer",
		attributes = {
			strength = 20,
			speed = 20,
			magic = 15,
			accuracy = 35,
			stealth = 20,
			constitution = 20,
		},
		titles = {
			"Fletcher",
			"Journeyman",
			"Page",
			"Squire",
			"Marksman",
			"Targetman",
			"Noble",
			"Sharpshooter",
			"Warrior",
			"Acurate",
			"Archer",
			"Forest Arrow",
			"CraftMaster",
			"Ancient Arrow",
			"Huntsman (1rd)",
			"Huntsman (2nd)",
			"Huntsman (3rd)",
			"Divine Missile",
			"Unerring One",
			"The Mighty"
		},
		advancement = {
			strength = 2,
			speed = 2,
			magic = 2,
			accuracy = 3,
			stealth = 1,
			constitution = 2,
		},
	},
	Sailor = {
		class = "Sailor",
		attributes = {
			strength = 25,
			speed = 25,
			magic = 10,
			accuracy = 20,
			stealth = 15,
			constitution = 35,
		},
		titles = {
			"Landlubber",
			"Trainee",
			"Galley Grunt",
			"Seaman",
			"Mate",
			"First Mate",
			"Sailor",
			"Veteran",
			"Captain",
			"Degree Hellespont",
			"Order of Salamis",
			"Golden Horn",
			"Seamaster",
			"Sextant Lord",
			"Admiral",
			"Water Magician",
			"Fury",
			"Order of Ulysses",
			"Prince of Havens",
			"Poseidon's Guide"
		},
		advancement = {
			strength = 2,
			speed = 2,
			magic = 1,
			accuracy = 2,
			stealth = 2,
			constitution = 3,
		},
	},
	Paladin = {
		class = "Paladin",
		attributes = {
			strength = 30,
			speed = 20,
			magic = 25,
			accuracy = 15,
			stealth = 10,
			constitution = 30,
		},
		titles = {
			"Page",
			"Squire",
			"Servant",
			"Good Knight",
			"The Annointed",
			"Blood Knight",
			"Warrior",
			"Son of Thunder",
			"Blessed Sword",
			"Crusader",
			"Champion",
			"Disciple",
			"Vanquisher",
			"Illuminated",
			"Cross Bearer",
			"Saint of Steel",
			"Soldier of God",
			"Avenger of God",
			"Wrath of God",
			"Hand of God"
		},
		advancement = {
			strength = 3,
			speed = 2,
			magic = 2,
			accuracy = 2,
			stealth = 1,
			constitution = 2,
		},
	},
	Mercenary = {
		class = "Mercenary",
		attributes = {
			strength = 30,
			speed = 20,
			magic = 10,
			accuracy = 25,
			stealth = 20,
			constitution = 25,
		},
		titles = {
			"Brawler",
			"Fighter",
			"Hireling",
			"Ransacker",
			"Wolf of War",
			"Soldier Fortune",
			"Destroyer",
			"Valorian Vitorix",
			"Legionaire",
			"Asassin",
			"Axe of Alesia",
			"Avenger",
			"Theo's Sword",
			"Siege Master",
			"Captain",
			"Son of Sparta",
			"The Janissary",
			"Hero",
			"ArmsMaster",
			"Casca"
		},
		advancement = {
			strength = 2,
			speed = 2,
			magic = 2,
			accuracy = 2,
			stealth = 2,
			constitution = 2,
		},
	},
	Magician = {
		class = "Magician",
		attributes = {
			strength = 15,
			speed = 30,
			magic = 30,
			accuracy = 20,
			stealth = 20,
			constitution = 15,
		},
		titles = {
			"Pupil",
			"Student",
			"Trickster",
			"Showman",
			"Charlatan",
			"Magician",
			"Deceiver",
			"Charmer",
			"Mystic",
			"Illusionist",
			"RuneMaster",
			"Seer",
			"Sage",
			"Dark Oracle",
			"Student of Rit",
			"Keeper of Rit",
			"Teacher of Rit",
			"Tower Artesian",
			"Master Sage",
			"Dark Prophet"
		},
		advancement = {
			strength = 1,
			speed = 3,
			magic = 3,
			accuracy = 2,
			stealth = 1,
			constitution = 2,
		},
	},
};

