# ------------------- Heading ---------------------
5,1,14,11,305,20,0,0,1,2,0,0,0,0,FontNormal
Options
ENDOFTEXT


# ------------------- Beginning List of Commands ---------------------
4,300,14,25,31,0,0
UI/3DUI/ESCMLINE
FontNormal
Resume Game

4,2001,14,36,31,0,0
UI/3DUI/ESCMLINE
FontNormal
Configure Keyboard

4,2007,14,47,31,0,0
UI/3DUI/ESCMLINE
FontNormal
Game Play

4,5000,14,58,31,0,0
UI/3DUI/ESCMLINE
FontNormal
Abort This Level and Go Back to Town!

